'use client';

import SiteHeader from '@/components/SiteHeader';
import { useEffect, useState } from 'react';
import { Headphones, Trash2, Upload } from 'lucide-react';

const empty = { title:'', artist:'', bpm:'', source_type:'upload', audio_url:'', cover_url:'', soundcloud_url:'', published:true };

export default function AdminDJ(){
  const [form,setForm]=useState<any>(empty),[tracks,setTracks]=useState<any[]>([]),[busy,setBusy]=useState('');
  const load=()=>fetch('/api/admin/dj-tracks',{cache:'no-store'}).then(async r=>{if(r.status===401)location.href='/login';if(r.status===403)location.href='/admin';if(r.ok)setTracks((await r.json()).tracks||[])});
  useEffect(()=>{load()},[]);
  const upload=async(kind:'cover'|'preview',file:File)=>{setBusy(`Uploading ${kind}…`);try{const sr=await fetch('/api/admin/upload/sign',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,name:file.name,contentType:file.type||'application/octet-stream',size:file.size})});const s=await sr.json();if(!sr.ok)throw new Error(s.error||'Upload failed');await new Promise<void>((ok,bad)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',s.signedUrl);xhr.onload=()=>xhr.status>=200&&xhr.status<300?ok():bad(new Error('Upload failed'));xhr.onerror=()=>bad(new Error('Network error'));xhr.send(file)});setForm((x:any)=>({...x,[kind==='cover'?'cover_url':'audio_url']:s.publicUrl}))}catch(e:any){alert(e.message||'Upload failed')}finally{setBusy('')}};
  const save=async()=>{setBusy('Saving…');const r=await fetch('/api/admin/dj-tracks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)alert(j.error||'Could not save');else{setForm(empty);await load()}setBusy('')};
  const del=async(id:string)=>{if(!confirm('Delete this DJ track?'))return;await fetch('/api/admin/dj-tracks?id='+id,{method:'DELETE'});load()};
  return <main><SiteHeader/><section className="admin-v4"><div className="admin-title"><div><span>OWNER / ADMIN PANEL</span><h1>DJ Library</h1></div><a className="secondary" href="/admin">Back to Studio</a></div><div className="admin-grid"><div className="panel"><h2><Headphones size={19}/> Add DJ track</h2><div className="form-grid"><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Artist<input value={form.artist} onChange={e=>setForm({...form,artist:e.target.value})}/></label><label>BPM<input type="number" value={form.bpm} onChange={e=>setForm({...form,bpm:e.target.value})}/></label><label>Source<select value={form.source_type} onChange={e=>setForm({...form,source_type:e.target.value})}><option value="upload">Uploaded audio</option><option value="soundcloud">SoundCloud</option></select></label></div>{form.source_type==='soundcloud'?<label className="wide-field">SoundCloud URL<input value={form.soundcloud_url} onChange={e=>setForm({...form,soundcloud_url:e.target.value})} placeholder="https://soundcloud.com/..."/></label>:<div className="upload-row one"><label className={form.audio_url?'done':''}><Upload size={16}/> DJ audio<input type="file" accept="audio/*" onChange={e=>e.target.files?.[0]&&upload('preview',e.target.files[0])}/></label></div>}<div className="upload-row one"><label className={form.cover_url?'done':''}><Upload size={16}/> Cover<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload('cover',e.target.files[0])}/></label></div><label className="check"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Available in DJ Studio</label><button className="primary square" onClick={save} disabled={!!busy||!form.title}>{busy||'Add to DJ Library'}</button></div><div className="panel"><h2>DJ tracks ({tracks.length})</h2><div className="admin-beat-list">{tracks.map(t=><div className="admin-beat" key={t.id}><img src={t.cover_url||'/her9al-logo.jpg'}/><div><b>{t.title}</b><span>{t.artist||'—'} · {t.bpm||'—'} BPM · {t.source_type}</span></div><button onClick={()=>del(t.id)}><Trash2 size={16}/></button></div>)}{!tracks.length&&<p className="muted">No DJ tracks yet.</p>}</div></div></div></section></main>
}
